name: cpp-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v2
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: gcc-latest
      - name: Install cmakes
        uses: lukka/get-cmake@latest
      - name: Install boost
        run: sudo apt-get install libboost-all-dev -y
      - name: Build
        run: cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=${{ steps.install_cc.outputs.cc }} -DCMAKE_CXX_COMPILER:FILEPATH=${{ steps.install_cc.outputs.cxx }} -H./ -B./build -G "Unix Makefiles"
        shell: bash
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
      
