name: cpp-formatter

on: [push]

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v2
    - name: C++ Style Check
      uses: coleaeason/actions-uncrustify@v1
